apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: horrorskope-external-api
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
        role: horrorskope-external-api
    spec:
      containers:
      - name: horrorskope-external-api
        image: jensneuse/k8s-demo:3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          port: 80
        env:
        - name: NAME
          value: "HorrorskopeExternalApi.v2 by @adrian mit Cache!!11"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "80"
        - name: IS_BACKEND
          value: "true"
