apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: weather-external-api
spec:
  selector:
    matchLabels:
      app: demo2
  replicas: 2
  template:
    metadata:
      labels:
        app: demo2
        role: weather-external-api
    spec:
      containers:
      - name: weather-external-api
        image: jensneuse/k8s-demo:4.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          port: 80
        env:
        - name: NAME
          value: "WeatherExternalApi.v1"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "80"
        - name: IS_BACKEND
          value: "true"
        - name: BACKEND_LATENCY
          value: "1"
