apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: backend
spec:
  match:
    source:
      name: frontend-service
  destination:
    name: backend-service
  precedence: 1
  route:
  - labels:
      app: demo
      role: backend
  httpFault:
   abort:
     percent: 50
     httpStatus: 500