apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: frontend
spec:
  destination:
    name: frontend-service
  precedence: 1
  route:
  - labels:
      app: demo2
      role: frontend
      version: 1.0.0