apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: demo-frontend-deployment
spec:
  selector:
    matchLabels:
      app: demo2
  replicas: 2
  template:
    metadata:
      labels:
        app: demo2
        role: frontend
        version: 1.0.0
    spec:
      containers:
      - name: frontend
        image: jensneuse/k8s-demo:1.0.0
        ports:
        - containerPort: 80
          port: 80
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "80"
        - name: IS_BACKEND
          value: "false"
        - name: BACKEND_URL
          value: "http://backend-service"
