apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: renderine
spec:
  selector:
    matchLabels:
      app: renderine
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
        role: renderine
        version: 3.0.0
    spec:
      containers:
      - name: renderine
        image: jensneuse/k8s-demo:3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          port: 80
        env:
        - name: NAME
          value: "Renderine by @Enno"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "80"
        - name: IS_BACKEND
          value: "false"
        - name: BACKEND_URL
          value: "http://database,http://horrorskope-api,http://weather-api"
